### ISSUE TITLE
请新增requirements.txt文件

### ISSUE THREAD

**Issue by shibing624** [CLUEbenchmark/CLUENER2020#1]
指明TensorFlow版本，和pytorch版本

**Comment by brightmart** [comment]
TensorFlow版本是1.x, 如1.14

**Comment by ConnieTong** [comment]
Tensorflow 1.10版本会报错
TypeError: Input 'y' of 'Maximum' Op has type int64 that does not match type int32 of argument 'x'

**Comment by ConnieTong** [comment]
把train_sequence_label.py Line 86-87 改成
viterbi_sequence, viterbi_score = tf.contrib.crf.crf_decode(
            logits, transition_matrix, tf.cast(input_m, tf.int32))
即可

**Comment by brightmart** [comment]
不错

**Comment by ermu-tech** [comment]
请问这个是在什么系统下运行的呢？
