### ISSUE TITLE
论文中统计最大句长为50，但是Max Length设置为128，请问一下这样做的原因是什么？效果有提升吗？

### ISSUE THREAD

**Issue by ConnieTong** [CLUEbenchmark/CLUENER2020#15]
论文中统计最大句长为50，但是Max Length设置为128，请问一下这样做的原因是什么？效果有提升吗？

谢谢

**Comment by lonePatient** [comment]
@ConnieTong 习惯写法了吧 里面加了collect_fn，动态调整batch长度 不影响的
