### ISSUE TITLE
请问能提供训练好了的checkpoint吗？

### ISSUE THREAD

**Issue by HsiaYu** [CLUEbenchmark/CLUENER2020#16]

**Comment by brightmart** [comment]
你是tensorflow还是pytorch？

**Comment by HsiaYu** [comment]
都行。如果可以直接提供训好的checkpoint最好啦~没有也没关系

**Comment by lonePatient** [comment]
@HsiaYu 这个还真没有，是跑出结果差距大还是？cluener数据不是很大，我觉得直接微调下。

**Comment by zhouhui1992** [comment]
用tensorflow训练了bert_base，使用的是默认参数，但是预测的时候输出完全错了，预训练模型用的是google提供的chinese_L-12_H-768_A-12，请教下问题可能出在哪？

**Comment by zhouhui1992** [comment]
tensorflow 版本由1.12.0改成1.14.0 没问题了。
