### ISSUE TITLE
“pooled_output = self.dropout(pooled_output+0.1)” is confusing

### ISSUE THREAD

**Issue by matricer** [CLUEbenchmark/CLUENER2020#17]
the pytorch code in AlbertForSequenceClassification is confusing
![image](https://user-images.githubusercontent.com/16053879/76403140-6ef9f600-63bf-11ea-9f5d-1aa92550999b.png)
why use "pooled_output = self.dropout(pooled_output+0.1)" rather than "pooled_output = self.dropout(pooled_output)"

**Comment by lonePatient** [comment]
@matricer albert配置文件dropout为0.0，对已微调而言，数据不大一般会过拟合，加上0.1效果会好点
