### ISSUE TITLE
pytorch 版的spanbert的mask定义在哪个文件啊  没有找到呢

### ISSUE THREAD

**Issue by heroazhe** [CLUEbenchmark/CLUENER2020#19]

**Comment by lonePatient** [comment]
@heroazhe ？？ 这个不是spanBERT模型啊，中文版好像也没有spanbert。英文版你可以看下https://github.com/facebookresearch/SpanBERT

**Comment by heroazhe** [comment]
那这个里面的bert + span是什么意思？

**Comment by heroazhe** [comment]
哦，还有个问题想问一下，你是怎么理解end_logits的计算方法的？  有点不是很理解，通过一个end_fc就算出来了。

**Comment by heroazhe** [comment]
哦，还有个问题想问一下，你是怎么理解end_logits的计算方法的？&nbsp; 有点不是很理解，通过一个end_fc就算出来了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lonePatient"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 晚上6:23
收件人:&nbsp;"CLUEbenchmark/CLUENER2020"<CLUENER2020@noreply.github.com&gt;;
抄送:&nbsp;"FTD'2015"<690468229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [CLUEbenchmark/CLUENER2020] pytorch 版的spanbert的mask定义在哪个文件啊  没有找到呢 (#19)





 
@heroazhe ？？ 这个不是spanBERT模型啊，中文版好像也没有spanbert。英文版你可以看下https://github.com/facebookresearch/SpanBERT
