### ISSUE TITLE
CRF 的几点问题

### ISSUE THREAD

**Issue by ZacBi** [CLUEbenchmark/CLUENER2020#22]
https://github.com/CLUEbenchmark/CLUENER2020/blob/da6631c21d050309117ea28640c757bb46a1255e/pytorch_version/models/crf.py#L133-L150

既然tags已经是包含[CLS]和[SEP]的标签序列了, 为什么还要分别在左边和右边cat上[CLS]和[SEP]? 有点不解.

https://github.com/CLUEbenchmark/CLUENER2020/blob/da6631c21d050309117ea28640c757bb46a1255e/pytorch_version/models/crf.py#L41-L42
还有transition初始化是不是存在问题? 应该写成这样:
```python
self.transitions.detach()[:, :self.tag_dictionary[self.START_TAG]] = -10000
self.transitions.detach()[self.tag_dictionary[self.STOP_TAG]] = -10000 
```

**Comment by lonePatient** [comment]
@ZacBi 感谢反馈，第一个问题，回头我修改下，第二个应该是对的。

**Comment by tymanman** [comment]
第一个问题也没错，那里的tags是实际预测出的tag，长度等于序列长度，cat上start和end是为了形成错位，以便得到相应位置的上一个位置的转移概率
