### ISSUE TITLE
您这个ner只能是以下分类，我可以用您这个模型自定义分类吗？

### ISSUE THREAD

**Issue by passion765** [CLUEbenchmark/CLUENER2020#26]
您这个ner只能是以下分类，我可以用您这个模型自定义分类吗？
数据分为10个标签类别，分别为: 地址（address），书名（book），公司（company），游戏（game），政府（government），电影（movie），姓名（name），组织机构（organization），职位（position），景点（scene）

**Comment by lonePatient** [comment]
@passion765 没太理解你的意思，目前这个任务是针对ner，标签是固定死的，如果你想达到标签冷启动的话，可以看看opentag这种，一定程度上可以支持新属性提取。

**Comment by passion765** [comment]
你说的好像不太对， 我修改了标签也可以提取我想要的词。

**Comment by passion765** [comment]
> @passion765 没太理解你的意思，目前这个任务是针对ner，标签是固定死的，如果你想达到标签冷启动的话，可以看看opentag这种，一定程度上可以支持新属性提取。


你说的好像不太对， 我修改了标签也可以提取我想要的词。
