### ISSUE TITLE
关于span

### ISSUE THREAD

**Issue by ShallTearchen** [CLUEbenchmark/CLUENER2020#3]
请问一下span是什么意思？能不能给一下相关资料的链接 谢谢！

**Comment by lonePatient** [comment]
@ShallTearchen 您好，span模式当时是从qa或者mrc那边借鉴过来，预测实体的边界（答案的边界），解码不以CRF为主，在解决嵌套实体方面是非常好的，我记得19年下半年除了好几篇论文，你可以看看，不一定叫span，个人叫法而已。比如二元序列，啥的。

**Comment by ShallTearchen** [comment]
@lonePatient 非常感谢！

**Comment by ShallTearchen** [comment]
@lonePatient 抱歉！我还是没有找到您说的这个span模式 能不能麻烦您给一篇论文名

**Comment by lonePatient** [comment]
@ShallTearchen 比如这篇https://arxiv.org/pdf/1910.11476.pdf
