### ISSUE TITLE
关于init_logger(log_file)日志问题

### ISSUE THREAD

**Issue by CrazySadClown** [CLUEbenchmark/CLUENER2020#41]
pytorch_verion 里 run_ner_crf.py 389行没法正确的创建log文件 

#对args.output_dir目录下创建一个日志文件
    # init_logger(log_file= args.output_dir + f'/{args.model_type}-{args.task_name}-{time_}.log')
    init_logger(log_file=str('{}-{}-{}.log'.format(args.model_type, args.task_name,time_)))
    # init_logger(log_file=str(args.output_dir / '{}-{}.log'.format(args.arch, args.task_name)))

报错： 
OSError: [Errno 22] Invalid argument: 'E:\\aDemo\\NNNER\\bert\\pytorch\\pytorch_version\\outputs\\cluener_output\\bert\\bert-cluener-2020-09-09-13:36:12.log"
试了多种方法都不行

**Comment by lonePatient** [comment]
公开的脚本都是在linux在测试下 ，window下应该是路径分隔符的问题吧
