### ISSUE TITLE
你好，请问这个CnerProcessor里标签'X',"[START]", "[END]"是用来做什么的？

### ISSUE THREAD

**Issue by algoflow19** [CLUEbenchmark/CLUENER2020#44]
https://github.com/CLUEbenchmark/CLUENER2020/blob/b6597268c000e06aa95bcdc59ef122805254cab6/pytorch_version/processors/ner_seq.py#L158-L177

**Comment by lmw0320** [comment]
同问。。
我查了下ner的标签，'X', 'START', 'END'并没有用到。。是为了方便BIOES或是其他标注方式而额外事先配置的？

**Comment by lxgend** [comment]
> 同问。。
> 我查了下ner的标签，'X', 'START', 'END'并没有用到。。是为了方便BIOES或是其他标注方式而额外事先配置的？
> 就是‘X’不理解作为什么类别标签用。。

X可以作为padding的标签

**Comment by algoflow19** [comment]
奥奥，所以分别是给 [PAD] [CLS] [SEP] 使用的是吗？明白了谢谢
