### ISSUE TITLE
数据集下载链接无法打开？

### ISSUE THREAD

**Issue by NiuQian** [CLUEbenchmark/CLUENER2020#45]
rt，在readme文件中，有数据集下载的链接（http://www.cluebenchmark.com/introduce.html）但是我无法打开这个链接。
请问数据集是免费的吗？应该如何获取

**Comment by brightmart** [comment]
你好。下面这个数据集的下载地址，是可以打开的呢：
https://storage.googleapis.com/cluebenchmark/tasks/cluener_public.zip
