### ISSUE TITLE
训练pytorch_version报错

### ISSUE THREAD

**Issue by lmw0320** [CLUEbenchmark/CLUENER2020#51]
训练命令： python run_ner_crf.py --task_name cluener --data_dir /home/lmw/deep_learning_data/train/NLP/cluene_data --model_type bert --model_name_or_path bert-base-cased --output_dir /home/lmw/deep_learning_data/model_files_ner

报错如下：（里面的几个基本参数设置，我有点不太明白：--task_name 貌似只有一个选项 cluener? 而 model_type也只有2个选项：bert和albert。 对于model_name_or_path，我是以为有预训练模型可以加载，没有就从头开始训练。。结果貌似不是，会自动从网上去下载相应的vocab.txt文件。。）我是个初学者，建议readme里面能够描述更清楚点，谢谢了～
![2](https://user-images.githubusercontent.com/37755235/103400307-96ed5c80-4b7f-11eb-9435-f09286c07d92.png)

**Comment by lmw0320** [comment]
忘记说了，我的环境是ubuntu18.04， pytorch1.5.0, cuda10.1 ---（我后面搭建了个1.4.0的pytorch环境，也是报相同的错误）

**Comment by yolanda182** [comment]
你好👋，请问这些参数您现在弄懂了吗

**Comment by brightmart** [comment]
@lonePatient
