### ISSUE TITLE
关于pytorch的模型保存和预测的疑问

### ISSUE THREAD

**Issue by lmw0320** [CLUEbenchmark/CLUENER2020#54]
我跑通了pytorch_version中的run_ner_crf.py，发现几个问题：
1. 训练阶段，根据前期设定的参数，模型的相关文件会保存到指定的文件夹中。但是，相应的文件存在不少重复，比如vocab.txt和config.json，不知道是否可以改到原始代码中的文件夹中。因为预测和训练其实都要使用这两份文件，感觉没必要一直保存。
2. 对于模型保存的optimizer.pt文件，每个都比较大，有800多M。如果保存的次数较多，很占用空间，不知道是否可以不保存该文件？--感觉这个文件，在预测阶段貌似并没用。
3. 我想设置下断点训练，即训练中断，可以直接从相应的模型文件中去加载，不知道原代码是否可以实现？
4. 进行预测的时候，我看提示中还显示去加载预训练模型？这个感觉没必要吧？保存下来的pytorch_model.bin文件中，是否已经包含了config.jsonz中的内容，我尝试过，只要这个bin文件和vocab.txt就可以完成预测的。

**Comment by lonePatient** [comment]
@lmw0320 您好，1. 重新保留vocab和config在同一个目录，是为了方便制定model_path之后，脚本直接读取，不同在分别制定vocab的路径以及config的路径。2. optimizer保存的确很大，只是为了断点训练，一般情况下是使用不到了，你可以见到修改下save_pretrained就可以了，不是很难。3. 只有满足前两个，那个断点训练是没有问题的，直接指定checkpoint目录即可。4. 预测时候可以初始化一个空的，或者你将脚本简单修改下，from_predtrain在do_train和do_predict分别使用一次即可。根据具体需求或者场景定制化代码吧。

**Comment by lmw0320** [comment]
> @lmw0320 您好，1. 重新保留vocab和config在同一个目录，是为了方便制定model_path之后，脚本直接读取，不同在分别制定vocab的路径以及config的路径。2. optimizer保存的确很大，只是为了断点训练，一般情况下是使用不到了，你可以见到修改下save_pretrained就可以了，不是很难。3. 只有满足前两个，那个断点训练是没有问题的，直接指定checkpoint目录即可。4. 预测时候可以初始化一个空的，或者你将脚本简单修改下，from_predtrain在do_train和do_predict分别使用一次即可。根据具体需求或者场景定制化代码吧。

感谢答复。我后面自己调整了代码，目前已经基本实现自己的需求了。
只是还想请问下，这个config.json文件的保存，是在什么位置实现的？我一直找不到，后面是把config = config_class.from_pretrained获得的config变量，转成dict，才保存下来。。只是保存下来的这个config，和加载的config.json文件并不相同，还多了些其他参数。

**Comment by lonePatient** [comment]
@lmw0320 config保存时transformers模块里面自带的config保存，具体代码位于； https://github.com/CLUEbenchmark/CLUENER2020/blob/master/pytorch_version/models/transformers/configuration_utils.py

**Comment by lmw0320** [comment]
> @lmw0320 config保存时transformers模块里面自带的config保存，具体代码位于； https://github.com/CLUEbenchmark/CLUENER2020/blob/master/pytorch_version/models/transformers/configuration_utils.py

恩，感谢指点
