### ISSUE TITLE
get_entities_bois 有bug。 会多产生不必要的实体，并且没有去重。计算p,r,f 会不准确

### ISSUE THREAD

**Issue by jy007** [CLUEbenchmark/CLUENER2020#57]
seq = [[
        "O", "B-PER", "I-PER", "I-PER", "I-PER", "I-LOC", "I-LOC", "S-PER",
        "I-PER"
    ]]
    print(get_entities_bios(seq[0], None))

out:
[['PER', 1, 4], ['PER', 1, 4], ['PER', 1, 4], ['PER', 1, 4], ['PER', 1, 4], ['PER', 7, 7]]

**Comment by lonePatient** [comment]
@jy007 没有问题啊 ，测试出来是这个结果[['PER', 1, 4], ['PER', 7, 7]]
